### ISSUE TITLE
@Hannibal046 - this is a great summary. Is there a more formal source for these LLMs?

### ISSUE THREAD

**Issue by BorisVis** [Hannibal046/Awesome-LLM#139]
@Hannibal046 - this is a great summary. Is there a more formal source for these LLMs?

**Comment by Hannibal046** [comment]
Hi, thanks for your interest! I believe the most **formal** source for each LLM is the corresponding official blog, such as [Meta](https://ai.meta.com/blog/), [Google](https://blog.google/technology/developers/). However, since [Huggingface](https://huggingface.co/models) integrates almost all open source LLM, you could always find the relevant information about each LLM there.
