### ISSUE TITLE
Add information about  ibm dromedary

### ISSUE THREAD

**Issue by bharathrajcl** [Hannibal046/Awesome-LLM#29]
please add this model info

https://mitibmdemos.draco.res.ibm.com/dromedary

**Comment by Hannibal046** [comment]
Hi, thanks for bring attention to this paper. 


Since i am not very familiar with it, would you mind making a PR for it?













程信




发件人：bharathrajcl ***@***.***>
发送日期：2023-05-08 17:16:12
收件人：Hannibal046/Awesome-LLM ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[Hannibal046/Awesome-LLM] Add information about ibm dromedary (Issue #29)

please add this model info
https://mitibmdemos.draco.res.ibm.com/dromedary

**Comment by Hannibal046** [comment]
Done. Thanks again for bring this paper to Awesome-LLM!
